openapi: 3.0.0
info:
  title: Full Funnel Analytics API
  description: API for querying campaign analytics data
  version: 1.0.0
servers:
  - url: https://fullfunnelmu.netlify.app
paths:
  /chatgpt/query:
    post:
      summary: Query campaign analytics data
      operationId: queryCampaigns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Natural language query for analytics
                filters:
                  type: object
                  properties:
                    dateRange:
                      type: object
                      properties:
                        start:
                          type: string
                          format: date
                        end:
                          type: string
                          format: date
                    eventType:
                      type: string
                    city:
                      type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis:
                    type: string
                  aggregateMetrics:
                    type: object
                  campaigns:
                    type: array
                    items:
                      type: object
