openapi: 3.1.0
info:
  title: Full Funnel Analytics API
  description: API for querying campaign analytics data
  version: 1.0.0

servers:
  - url: https://fullfunnelmu.netlify.app

# Apply API key globally so the Action always injects it
security:
  - ApiKeyAuth: []

paths:
  /api/chat/query:
    post:
      summary: Query campaign analytics data
      operationId: queryCampaigns
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required: [message]
              properties:
                message:
                  type: string
                  description: Natural language query for analytics
                filters:
                  type: object
                  properties:
                    dateRange:
                      type: object
                      properties:
                        start:
                          type: string
                          format: date
                        end:
                          type: string
                          format: date
                    eventType:
                      type: string
                    city:
                      type: string
      responses:
        "200":
          $ref: "#/components/responses/SuccessJSON"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    QueryResponse:
      type: object
      properties:
        message:
          type: string
        query:
          type: string
        collections:
          type: array
          items:
            type: string
        sampleData:
          type: array
          items:
            type: object
            additionalProperties: true
        status:
          type: string

  responses:
    SuccessJSON:
      description: Successful response
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/QueryResponse"
    BadRequest:
      description: Bad request
    Unauthorized:
      description: Unauthorized
    ServerError:
      description: Server error
